target("tuesdays-core-utils")
    set_kind("static")
    add_files("utils/**.cpp")
    add_packages("imgui-sfml", "spdlog", { public = true })

target("tuesdays-core-components")
    set_kind("static")
    -- add_files("components/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-utils")
    add_packages("imgui", { public = true })

target("tuesdays-core-engine")
    set_kind("static")
    add_files("engine/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-utils")
    add_packages("imgui-sfml", "spdlog", { public = true })

target("tuesdays-core-luaren")
    set_kind("static")
    add_files("luaren/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-utils")
    add_packages("lua", "imgui-sfml", "spdlog", { public = true })

target("tuesdays-core-globals")
    set_kind("static")
    add_files("globals/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-engine")
    add_packages("spdlog", { public = true })

target("tuesdays-core-lifetimes")
    set_kind("static")
    add_files("lifetimes/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-globals", "tuesdays-core-engine")
    add_packages("imgui-sfml", "spdlog", { public = true })

target("tuesdays-core-keys")
    set_kind("static")
    add_files("keys/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-globals", "tuesdays-core-utils")
    add_packages("sfml", "spdlog", { public = true })

target("tuesdays-core-layers")
    set_kind("static")
    -- add_files("layers/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-globals", "tuesdays-core-luaren", "tuesdays-core-utils")
    add_packages("imgui", "spdlog", { public = true })

target("tuesdays-core-tasks")
    set_kind("static")
    -- add_files("tasks/**.cpp")
    add_includedirs(".")
    add_deps("tuesdays-core-globals", "tuesdays-core-utils")
    add_packages("imgui", "spdlog", { public = true })
